version: '3'
services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    restart: always

  attacker:
    container_name: juice-attacker
    build: ./attacker
    tty: true